name: auth_01
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg:

  firebase_core: ^2.24.2
  cloud_firestore:
  firebase_auth:

  modal_progress_hud_nsn:
  confetti:

  path_provider:
  provider:

  flutter_slidable:
  custom_refresh_indicator: ^3.0.0

  mailer:
  image_picker:

  flutter_mailer: ^2.1.2
  widgets_to_image: ^0.0.2

  #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
